version: '3.8'

services:
  dns-servm:
    image: dns-lab-debian:trixie-serv
    container_name: dns-servm
    hostname: ns1
    restart: always
    volumes:
      - ./bind:/etc/bind
    command: ["named", "-g", "-c", "/etc/bind/named.conf"]
    networks:
      lab-net:
        ipv4_address: 172.18.0.2   # ns1

  dns-servl:
    image: dns-lab-debian:trixie-serv
    container_name: dns-servl
    hostname: ns2
    restart: always
    volumes:
      - ./bind-nsl:/etc/bind
    command: ["named", "-g", "-c", "/etc/bind/named.conf"]
    networks:
      lab-net:
        ipv4_address: 172.18.0.3   # ns2

  dns-client:
    image: dns-lab-debian:trixie
    container_name: dns-client
    restart: always
    networks:
      lab-net:
        ipv4_address: 172.18.0.4   # ns1

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
